export default [
  // { category: "!NEEDS FURTHER INVESTIAGION", match: "Global-E Online Ltd" },
  { category: "!NEEDS FURTHER INVESTIAGION", match: "L. Koivogui" },
  { category: "travel", match: "Global Collect BV" },
  { category: "travel", match: "ADINA HAMBURG" },
  { category: "travel", match: "KLASS WAGEN" },
  { category: "travel", match: "GlobalCollect" },
  { category: "travel", match: "PORTURIST" },
  { category: "travel", match: "HMS Host International" },
  { category: "travel", match: "HOTEL BERGHOF" },
  { category: "travel", match: "Transavia" },
  { category: "travel", match: "Travix" },
  { category: "travel", match: "TREKKSOFT" },
  { category: "travel", name: "DisneyLand Paris", match: "EURODISNEY" },
  { category: "travel", name: "DisneyLand Paris", match: "DISNEY CONTACTLESS" },
  {
    category: "travel",
    name: "DisneyLand Paris",
    match: "DISNEY PREMIER ACCESS",
  },
  { category: "travel", match: "RATBV" },
  { category: "travel", match: "STB SA BUCURESTI" },
  { category: "travel", name: "Cazare Grecia", match: "Stelianos" },
  { category: "travel", match: "KLM" },
  { category: "travel", match: "TRIPAIR" },
  { category: "travel", name: "Restaurant", match: "BILUM BRAND" },
  { category: "travel", match: "Kroonenberg Groep" },
  { category: "travel", match: "Landal Miggelenberg" },
  { category: "travel", match: "LANDAL.NL" },
  { category: "travel", match: "VILA COTROCENI" },
  { category: "travel", match: "KISSANDFLY.RO" },
  { category: "travel", name: "Groceries", match: "MEGAIMAGE" },
  {
    category: "travel",
    name: "Cazare Zorilor, Brasov",
    match: "STR.ZORILOR NR.6",
  },
  { category: "travel", match: "LUCHTHAVEN Schip" },
  { category: "travel", match: "REWE" },
  { category: "travel", match: "ATM" },
  { category: "travel", match: "Flights on Booking.com" },
  { category: "travel", name: "Restaurant LEMONOKIPOS", match: "LEMONOKIPOS" },
  { category: "travel", match: "motel" },
  {
    category: "travel",
    name: "Echipamente Ski Austria",
    match: "Sport Wegscheider",
  },
  {
    category: "travel",
    name: "Telecabina Austria",
    match: "Penkenbahn",
  },
  {
    category: "travel",
    name: "Scoala Ski Austria",
    match: "SMT Mayrhofen",
  },
  { category: "travel", match: "MYTRIP" },
  { category: "travel", match: "RENTALCARS.COM" },
  { category: "travel", match: "RENT-A-CAR" },
  { category: "travel", match: "Schiphol" },
  { category: "travel", match: "STG ADYEN" },
  { category: "travel", match: "TAROM" },
  { category: "travel", match: "WIZZ" },
  { category: "travel", match: "BLUEAIRWEB" },
  { category: "travel", match: "AIRBNB" },
  { category: "travel", match: "Wilde  Moeflon" },
  { category: "travel", match: "ZAGAZAGA" },
  { category: "travel", match: "FERMA PENTELEU" },
  { category: "travel", name: "FERMA PENTELEU", match: "FERMAPENTEL" },
  { category: "travel", name: "Madrid", match: "IBEXPRESS060230491260" },
  { category: "travel", name: "Booking.com", match: "Hotel at Booking.com" },
  { category: "travel", match: "Omschrijving: Tenerife" },
  { category: "travel", match: "hotel" },
  { category: "travel", name: "Payments in Romania", match: "Land: RO" },
  { category: "travel", name: "Payments in Greece", match: "Land: GR" },
  { category: "travel", name: "Payments in Germany", match: "Land: DE" },
  { category: "travel", name: "Payments in Italy", match: "Land: IT" },
  { category: "travel", name: "Payments in France", match: "Land: FR" },
  { category: "travel", name: "Payments in Portugal", match: "Land: PT" },
  { category: "travel", name: "Payments in Belgium", match: "Land: BE" },
  { category: "travel", name: "Payments in Poland", match: "Land: PL" },
  { category: "travel", name: "Payments in Austria", match: "Land: AT" },
  { category: "travel", name: "Payments in Spain", match: "Land: ES" },
  { category: "travel", name: "Payments abroad", match: "Land: " },
  { category: "bank fees", match: "Your monthly statement is" },
  { category: "beauty", match: "PPopNL" },
  { category: "beauty", match: "CLINIC PURE" },
  { category: "beauty", match: "The Wax Bar" },
  { category: "beauty", match: "LAKWERK" },
  { category: "beauty", match: "GLOW2GO" },
  { category: "beauty", match: "waxingthecity" },
  { category: "beauty", match: "COTTON SPA STORE" },
  { category: "bike", match: "Dolly" },
  { category: "bike", match: "VANMOOFBV" },
  { category: "bike", match: "Bobike" },
  { category: "bike", name: "Adaptoare Dolly", match: "Angeliek" },
  { category: "books", match: "AMERICAN BOOK CENTER" },
  { category: "car", match: "ANWB" },
  { category: "car", name: "taxes", match: "REMI/SH-004-X" },
  { category: "car", name: "Amenda", match: "CJIB" },
  { category: "car", match: "Centraal Beheer" },
  { category: "car", match: "FRANK VANEMAN AUTO" },
  { category: "car", name: "Fuel", match: "SHELL" },
  { category: "car", match: "Veilig B.V." },
  { category: "car", match: "Abswoude" },
  { category: "car", match: "Wisselautomaten.nl" },
  { category: "car", match: "Loogman" },
  { category: "car", match: "PI ZD Zentrale Bußgeldstelle" },
  { category: "car", match: "Loogman Tanken" },
  { category: "car", name: "Parking", match: "Parkeren" },
  { category: "car", name: "Fuel", match: "TOTAL THORBECKEWEG" },
  { category: "car", name: "Parking", match: "Parkeergarage" },
  { category: "car", match: "GARAGE QUICK SERVICE" },
  { category: "car", match: "Garagebedrijf" },
  { category: "car", name: "Parking", match: "Parking" },
  { category: "car", name: "Parking", match: "ParkBee" },
  { category: "car", name: "Parking", match: "Parkmobile" },
  { category: "car", name: "Fuel", match: "ESSO AMSTERDAM" },
  { category: "car", name: "Fuel", match: "ESSO Express" },
  { category: "car", name: "Parking", match: "MOBILITEITSGELDEN" },
  { category: "cash", match: "AANKOMST SCHIPHOL PLAZA" },
  { category: "cash", match: "Geldmaat" },
  { category: "cash", match: "ING AMSTERDAM" },
  { category: "cash", match: "ING SCHIPHOL PLAZ" },
  { category: "cash", match: "JAN VAN GALENSTR 86" },
  { category: "cash", match: "JODENBREESTRAAT 96" },
  { category: "cash", match: "UTRECHTSESTRAAT 13" },
  { category: "charity", match: "Stichting Save the Children" },
  { category: "charity", match: "ESA HUMANITARIAN" },
  { category: "charity", match: "Wikimedia" },
  { category: "childcare", match: "CompaNanny" },
  { category: "childcare", match: "KinderRijk" },
  { category: "childcare", match: "Kids Aktief" },
  { category: "childcare", match: "TOESLAGEN" },
  { category: "cleaning", match: "Carolina Robayo Correa" },
  { category: "clothes", match: "Bever" },
  { category: "clothes", match: "OYSHO" },
  { category: "clothes", match: "LeeWrangler" },
  { category: "clothes", match: "La Redoute" },
  { category: "clothes", match: "Sonali Casuals" },
  { category: "clothes", match: "The Tropic Feel " },
  { category: "clothes", match: "WOMENSECRET" },
  { category: "clothes", match: "IELM.RO" },
  { category: "clothes", match: "DIESEL STORE" },
  { category: "clothes", match: "Skechers" },
  { category: "clothes", match: "ESPRIT" },
  { category: "clothes", match: "Limango" },
  { category: "clothes", match: "NELSON G-PLEIN" },
  { category: "clothes", match: "Onitjuka Tiger" },
  { category: "clothes", match: "UNIQLO" },
  { category: "clothes", name: "H&M", match: "H & M" },
  { category: "clothes", match: "H&M" },
  { category: "clothes", match: "Nike" },
  { category: "clothes", match: "Adidas" },
  { category: "clothes", match: "Zalando" },
  {
    category: "clothes",
    name: "Adidas",
    match: "4316234027037875 ",
  },
  { category: "clothes", match: "Veepee" },
  { category: "clothes", name: "Veepee", match: "VenteExclusive" },
  { category: "clothes", match: "C&A" },
  { category: "clothes", name: "C&A", match: "CenA" },
  { category: "clothes", name: "C&A", match: "C+amp,A" },
  { category: "clothes", match: "ARKET" },
  { category: "clothes", match: "Boozt.com" },
  { category: "clothes", match: "Zara" },
  { category: "clothes", name: "Zara", match: "Fashion Retail SA" },
  { category: "clothes", name: "Zara", match: "FASHION RETAIL S.A." },
  { category: "clothes", match: "URBAN OUTFITTERS" },
  { category: "clothes", name: "WE", match: "wefashion.nl" },
  { category: "clothes", name: "WE", match: "WE Fashio" },
  {
    category: "clothes",
    name: "Limango",
    match: "STICHTING DERDENGELDEN BUCKAROO",
  },
  { category: "coffee", match: "Back To Black" },
  { category: "coffee", name: "Monk COFFEE", match: "ZCB PARK CAFE" },
  { category: "coffee", match: "Badeta Coffee" },
  { category: "coffee", match: "BOABE SI STRUGURI" },
  { category: "coffee", match: "BOCA" },
  { category: "coffee", match: "BRANDMEESTER" },
  { category: "coffee", match: "BREAD & SPICES" },
  { category: "coffee", match: "Cafe Nord" },
  { category: "coffee", match: "Caffe Minerva" },
  { category: "coffee", match: "Caffenation" },
  { category: "coffee", match: "Cafecito" },
  { category: "coffee", match: "Coffee Bru" },
  { category: "coffee", match: "Coffee Comp" },
  { category: "coffee", match: "Coffee District" },
  { category: "coffee", match: "CoffeeCompany" },
  { category: "coffee", match: "De Uitsmijter" },
  { category: "coffee", match: "Gogol BV" },
  { category: "coffee", match: "Guji B.V." },
  { category: "coffee", match: "Loco Concepts" },
  { category: "coffee", match: "VASCOBELO" },
  { category: "coffee", match: "YUSU" },
  { category: "coffee", name: "Coffee District", match: "Coffee Distri" },
  { category: "coffee", name: "Lebkov&Sons", match: "Lebkov@Sons" },
  {
    category: "coffee",
    name: "Scandinavian Embassy",
    match: "Scandinavian Embassy",
  },
  {
    category: "coffee",
    name: "Scandinavian Embassy",
    match: "SumUp Scandinavian",
  },
  {
    category: "coffee",
    name: "Scandinavian Embassy",
    match: "ScandinavianEmbassy",
  },

  { category: "coffee", match: "Coffee" },
  { category: "coffee", match: "Cafea" },

  { category: "entertainment", match: "Paradiso" },
  { category: "creditcard", match: "INT CARD SERVICES" },
  { category: "creditcard", match: "International Card Services B.V." },
  { category: "crypto", match: "transak.com" },
  { category: "crypto", match: "MOONPAY" },
  { category: "diy", match: "ToolMax.nl" },
  { category: "diy", match: "HORNBACH" },
  { category: "diy", match: "PeterPrint" },
  { category: "diy", match: "Opencircuit" },
  { category: "diy", match: "PRUSA" },
  { category: "Doinita", match: "IFRIM DOINITA" },
  { category: "entertainment", match: "A Space Oddity" },
  { category: "entertainment", match: "Feestbazaar" },
  {
    category: "entertainment",
    name: "Tort Iris 5 ani",
    match: "RINistorNL78INGB07",
  },
  { category: "entertainment", match: "Jeugdland" },
  { category: "entertainment", match: "Amstelpark" },
  { category: "entertainment", match: "Amsterdam Spanish Film Festival" },
  { category: "entertainment", match: "ELEFANT.RO" },
  { category: "entertainment", match: "Artis" },
  { category: "entertainment", match: "ATHENAEUM SPUI" },
  { category: "entertainment", match: "ATHENAEUM SPUI" },
  { category: "entertainment", match: "Bibliotheek" },
  { category: "entertainment", match: "Boekhandel" },
  { category: "entertainment", match: "Bouldergym en Restaura" },
  { category: "entertainment", match: "CINEMACITY" },
  { category: "entertainment", match: "CINEPLEXX" },
  { category: "entertainment", match: "Concertgebouw" },
  { category: "entertainment", match: "EDENLAND" },
  { category: "entertainment", match: "EYE FILMINSTITUUT" },
  { category: "entertainment", match: "Julianatoren" },
  { category: "entertainment", match: "Kiddieland" },
  { category: "entertainment", match: "Bowling" },
  { category: "entertainment", match: "PONG" },
  { category: "entertainment", match: "Nationale Opera en Ballet" },
  { category: "entertainment", match: "Kriterion" },
  { category: "entertainment", match: "LANDAL GREENPARKS" },
  { category: "entertainment", match: "Museum" },
  { category: "entertainment", match: "MM Amsterdam Centrum" },
  { category: "entertainment", name: "Madurodam", match: "Madurod am" },
  { category: "entertainment", match: "NSC AMS" },
  { category: "entertainment", match: "OFFICIALMERCHANDISE" },
  { category: "entertainment", match: "OPENBARE BIBLIOT" },
  { category: "entertainment", match: "PAYPAL *NOLIMITES" },
  { category: "entertainment", match: "Space Expo" },
  { category: "entertainment", match: "Speeltuin Amstelpark" },
  {
    category: "entertainment",
    name: "Shared account with the Pops",
    match: "Naam: Hr P Pop",
  },
  {
    category: "entertainment",
    name: "Paul Pop",
    match: "/Hr P Pop/",
  },
  { category: "entertainment", match: "Pathe" },
  { category: "entertainment", match: "The New English Bookst" },
  { category: "entertainment", match: "Ticketmaster" },
  { category: "entertainment", match: "Floriade" },
  { category: "entertainment", match: "MIDGETGOLF" },
  { category: "entertainment", match: "De Nationale Theaterkassa" },
  { category: "entertainment", match: "Het Nationale Park" },
  { category: "entertainment", match: "AUDIBLE" },
  { category: "entertainment", match: "NETFLIX" },
  { category: "entertainment", match: "ITUNES.COM" },
  {
    category: "entertainment",
    name: "Kiddieland",
    match: "Ypex-Gelderlandpln",
  },
  { category: "entertainment", match: "Ziggo Dome" },
  { category: "entertainment", match: "VOXA.RO" },

  { category: "entrepreneurship", match: "King s day" },

  { category: "restaurant", match: "Asian Kitchen" },
  { category: "restaurant", match: "Bagels & Beans" },
  { category: "restaurant", match: "BAGELS AND BEANS" },
  { category: "restaurant", match: "BAGELS EN BEANS" },
  { category: "restaurant", match: "Bakhuys" },
  { category: "restaurant", match: "Bakkerij Lunchroom" },
  { category: "restaurant", match: "Bakkerskar" },
  { category: "restaurant", match: "Bakkerswinkel" },
  { category: "restaurant", match: "BAR BROUW" },
  { category: "restaurant", match: "Bar Moustache" },
  { category: "restaurant", match: "BAR PITA AMSTERDAM" },
  { category: "restaurant", match: "BeerTemple" },
  { category: "restaurant", match: "BIRD THAIS REST" },
  { category: "restaurant", match: "Blos Horeca" },
  { category: "restaurant", match: "Booking.com The Bank" },
  { category: "restaurant", match: "BRUG 34" },
  { category: "restaurant", match: "BruiZZ" },
  { category: "restaurant", match: "BURGER BAR" },
  { category: "restaurant", match: "BURGERIJ" },
  { category: "restaurant", match: "BURGERMEESTER" },
  { category: "restaurant", match: "BURGERZAKEN" },
  { category: "restaurant", match: "Cafe de Jaren" },
  { category: "restaurant", match: "Cafe De Raedt" },
  { category: "restaurant", match: "cafe Katoen" },
  { category: "restaurant", match: "CALIFORNIA BURRITO" },
  { category: "restaurant", match: "CANNIBALE" },
  { category: "restaurant", match: "CCV CAMEEL BV" },
  { category: "restaurant", match: "Chun Amsterdam" },
  { category: "restaurant", match: "Club Botanica" },
  { category: "restaurant", match: "de Doelen" },
  { category: "restaurant", match: "De Haven" },
  { category: "restaurant", match: "De Waldhoorn" },
  { category: "restaurant", match: "Delicatesse Shilla" },
  { category: "restaurant", match: "Deliveroo" },
  { category: "restaurant", match: "DeOudeDoelen" },
  { category: "restaurant", match: "Dim Sum Court" },
  { category: "restaurant", match: "DOMINOS" },
  { category: "restaurant", match: "DONER COMPANY" },
  { category: "restaurant", match: "Doner Plaza" },
  { category: "restaurant", match: "Eat Mode" },
  { category: "restaurant", match: "EAZIE" },
  { category: "restaurant", match: "FIER" },
  { category: "restaurant", match: "Limon B.V." },
  { category: "restaurant", match: "FOODHALLEN" },
  { category: "restaurant", match: "Fort Negen" },
  { category: "restaurant", match: "Fou Fow ramen" },
  { category: "restaurant", match: "Frozz B.V" },
  { category: "restaurant", match: "GASEROP" },
  { category: "restaurant", match: "Gasthuijs" },
  { category: "restaurant", match: "Gollem" },
  { category: "restaurant", match: "Good Fortune" },
  { category: "restaurant", match: "GRACECC.RO" },
  { category: "restaurant", match: "Grand Cafe de Balie" },
  { category: "restaurant", match: "Greenbrothers" },
  { category: "restaurant", match: "Greenwoods" },
  { category: "restaurant", match: "Happy italy" },
  { category: "restaurant", match: "HavenrestaurantTexel" },
  { category: "restaurant", match: "HEEREN" },
  { category: "restaurant", match: "HMSHOST AMSTERDAM SCHI" },
  { category: "restaurant", match: "Hong Kong Superstore" },
  { category: "restaurant", match: "Hoppy Days" },
  { category: "restaurant", match: "House of Bird" },
  { category: "restaurant", match: "Huize van Wely" },
  { category: "restaurant", match: "Hummbar" },
  { category: "restaurant", match: "Indian Quality" },
  { category: "restaurant", match: "Jabugo bar Iberico" },
  { category: "restaurant", match: "Jamin Amsterdam" },
  { category: "restaurant", match: "Joe And The Juice" },
  { category: "restaurant", match: "Julias" },
  { category: "restaurant", match: "Mex.Rest.Panchos" },
  { category: "restaurant", match: "Kam Yin" },
  { category: "restaurant", match: "Kohinoor" },
  { category: "restaurant", match: "Kopaczynska" },
  { category: "restaurant", match: "La Place" },
  { category: "restaurant", match: "LASTAGE" },
  { category: "restaurant", match: "Latei" },
  { category: "restaurant", match: "Le Big Fish" },
  { category: "restaurant", match: "LITTLE COLLINS" },
  { category: "restaurant", match: "Loetje" },
  { category: "restaurant", match: "Mana Mana" },
  { category: "restaurant", match: "MAOZ FALAFAL" },
  { category: "restaurant", match: "MAOZ FALAFEL" },
  { category: "restaurant", match: "MarleenKookt BV" },
  { category: "restaurant", match: "Martinot" },
  { category: "restaurant", match: "Mata Hari" },
  { category: "restaurant", match: "MC DONALDS" },
  { category: "restaurant", match: "McDonald" },
  { category: "restaurant", match: "MENEER TEMAKI" },
  { category: "restaurant", match: "Mezzave" },
  { category: "restaurant", match: "Moeders" },
  { category: "restaurant", match: "Moeke's Maaltijd" },
  { category: "restaurant", match: "Monkey Chief Tea" },
  { category: "restaurant", match: "MOOK PANCAKES" },
  { category: "restaurant", match: "MULTIFOODEXPRESS" },
  { category: "restaurant", match: "Nassau" },
  { category: "restaurant", match: "NENI Amsterdam" },
  { category: "restaurant", match: "NES CAFE" },
  { category: "restaurant", match: "NEW YORK PIZZA" },
  { category: "restaurant", match: "Noodlebar" },
  { category: "restaurant", match: "O mai Amsterdam" },
  { category: "restaurant", match: "OMELEGG" },
  { category: "restaurant", match: "OUDE ZIJDS HORECA" },
  { category: "restaurant", match: "Park Kiosk" },
  { category: "restaurant", match: "Pedevilla" },
  { category: "restaurant", match: "PELANGI GRILL" },
  { category: "restaurant", match: "PHO VIET" },
  { category: "restaurant", match: "Pizza Boys" },
  { category: "restaurant", match: "pizza" },
  { category: "restaurant", match: "Pizzabakkers" },
  { category: "restaurant", match: "pizzeria" },
  { category: "restaurant", match: "Poke Perfect" },
  { category: "restaurant", match: "Portare Via" },
  { category: "restaurant", match: "Praellokaal" },
  { category: "restaurant", match: "Puccini" },
  { category: "restaurant", match: "QUICK 747" },
  { category: "restaurant", match: "Radijs" },
  { category: "restaurant", match: "RAMEN YA" },
  { category: "restaurant", match: "ROEST" },
  { category: "restaurant", match: "SALSA SHOP" },
  { category: "restaurant", match: "Sky Food B.V." },
  { category: "restaurant", match: "SLA ASW" },
  { category: "restaurant", match: "Smulday Turkse" },
  { category: "restaurant", match: "Soup en Zo" },
  { category: "restaurant", match: "Starbuc" },
  { category: "restaurant", match: "STARBUCKS" },
  { category: "restaurant", match: "Storm B.V. ZANDVOORT" },
  { category: "restaurant", match: "Takumi Ramen Kitchen" },
  { category: "restaurant", match: "TAVERNA BARCELONA" },
  { category: "restaurant", match: "Teddy`s Grill" },
  { category: "restaurant", match: "Terrasmus" },
  { category: "restaurant", match: "THE BREAKFAST CLUB" },
  { category: "restaurant", match: "THE BUTCHER" },
  { category: "restaurant", match: "THE DUTCH CO" },
  { category: "restaurant", match: "The Food Loving" },
  { category: "restaurant", match: "The Rough Kitchen" },
  { category: "restaurant", match: "tHuis aan de Amstel" },
  { category: "restaurant", match: "Thuisbezorgd.nl" },
  { category: "restaurant", match: "UBER *EATS" },
  { category: "restaurant", match: "UBER EATS" },
  { category: "restaurant", match: "Urban Salad" },
  { category: "restaurant", match: "VAN DE BUURT" },
  { category: "restaurant", match: "Van Meggelen" },
  { category: "restaurant", match: "VAN T SPIT" },
  { category: "restaurant", match: "Van Wonderen Stroopwaf" },
  { category: "restaurant", match: "Venkel" },
  { category: "restaurant", match: "VERTREK 2/LOUNGE 2 2ET" },
  { category: "restaurant", match: "VIJZELSTRAAT BY TE A" },
  { category: "restaurant", match: "VITAMINSTORE" },
  { category: "restaurant", match: "Vlaamsch Broodhuys" },
  { category: "restaurant", match: "Vof Blaauwhooft" },
  { category: "restaurant", match: "Volendammer Vishande" },
  { category: "restaurant", match: "Wagamama" },
  { category: "restaurant", match: "Winkel 43" },
  { category: "restaurant", match: "Wok To Go" },
  { category: "restaurant", match: "YOGEN FRUZ" },
  { category: "restaurant", match: "Ysbreker" },
  { category: "restaurant", match: "ZUCCA LEIDEN" },
  { category: "restaurant", match: "FLOR DO CAFE" },
  { category: "restaurant", match: /^Febo/ },
  { category: "restaurant", match: /BRASSERIE/i },
  { category: "restaurant", match: /cafe/i },
  { category: "restaurant", match: /horeca/i }, // https://en.wikipedia.org/wiki/Hor
  { category: "restaurant", name: "Bagels and Beans", match: "SALOMON LUNCH" },
  { category: "restaurant", name: "Bar Jones", match: "DE BRAKKE GROND" },
  { category: "restaurant", name: "Burger King", match: "BK 13462" },
  { category: "restaurant", name: "Cafe De Klos", match: "BGN WEST BV" },
  {
    category: "restaurant",
    name: "Elsevier Cafe",
    match: "Reed Elsevier A'dam",
  },
  { category: "restaurant", name: "Hutten Business", match: "Hutten Business" },
  { category: "restaurant", name: "Lucky House", match: "Lucky House" },
  { category: "restaurant", name: "Restaurant", match: /RESTAURANT/i },
  { category: "restaurant", name: "Vlad's friends", match: "AJ OWEN" },
  { category: "restaurant", name: "Vlad's friends", match: "IC Polli" },
  {
    category: "restaurant",
    name: "Vlad's friends",
    match: "J. Rovira I Bonet",
  },
  { category: "restaurant", name: "Vlad's friends", match: "Mamas & Tapas" },
  { category: "restaurant", name: "Vlad's friends", match: "Marcell" },
  { category: "restaurant", name: "Vlad's friends", match: "Rovira i Bonet" },
  { category: "restaurant", name: "Vlad's friends", match: "VERSCHAEREN" },
  { category: "restaurant", name: "Wannemakers!", match: "Zhu Lin VOF" },
  {
    category: "restaurant",
    name: "Wok To Walk Dam",
    match: "CCV WOK DAMSTRAAT",
  },
  { category: "restaurant", name: "Wok To Walk", match: "DOV MELO" },
  { category: "restaurant", note: "burgers", match: "Prime Cuts BV" },
  { category: "restaurant", note: "near", match: "Corner Admiraal" },

  { category: "friends", match: "MO MARIN" },
  { category: "friends", match: "Oana" },
  { category: "friends", match: "EDROI" },
  { category: "friends", match: "Bridinel" },
  { category: "friends", match: "Catalin" },
  { category: "friends", match: "Sandu Irina" },
  { category: "friends", name: "Sandu Irina", match: "Irina - Ana Sandu" },
  { category: "friends", match: "Homorozeanu" },
  { category: "friends", match: "Poschina" },
  { category: "friends", match: "Piftor" },
  { category: "friends", match: "C Stancu" },
  { category: "friends", match: "OPop" },

  { category: "gifts", match: "Babypark Kesteren BV" },
  { category: "gifts", name: "Woom 4", match: "Order van winkelwagen:214286" },
  { category: "gifts", match: "Siebel Juweliers" },
  { category: "gifts", match: "Bloemen" },
  { category: "gifts", match: "Happy Print" },
  { category: "gifts", match: "Amsterdam Flowers" },
  { category: "gifts", match: "Koffiejongens" },
  { category: "gifts", match: "Douglas" },
  { category: "gifts", match: "LOCO FABRIEK" },
  { category: "gifts", match: "YourSurprise.com" },
  { category: "gifts", match: "Zwaan en van Slooten" },
  { category: "gifts", match: "Rituals" },
  { category: "gifts", match: "INTERTOYS" },
  { category: "gifts", match: "Cedille" },
  { category: "gifts", match: "Livehelfi" },
  { category: "gifts", match: "Belevenissen.nl" },
  { category: "gifts", match: "Kids Toys World" },
  { category: "gifts", match: "resengo.com" },
  { category: "gifts", match: "Greetz.nl" },
  { category: "gifts", match: "fond of" },
  { category: "gifts", match: "Jacki s 70th" },
  { category: "gifts", name: "Myrna", match: "MSomberg" },
  { category: "groceries", name: "Albert Heijn", match: "AH to go" },
  { category: "groceries", match: "Holland & Barrett" },
  { category: "groceries", match: "Makro" },
  { category: "groceries", match: "BEBETEI" },
  { category: "groceries", match: "GARDEN OF LIFE" },
  { category: "groceries", match: "FRESHFUL.RO" },
  { category: "groceries", match: "Albert Heijn" },
  { category: "groceries", name: "Albert Heijn", match: "NL73INGB0008936868" },
  { category: "groceries", match: "Ankara Market" },
  { category: "groceries", match: "Crowdbutching.com" },
  { category: "groceries", match: "Gall & Gall" },
  { category: "groceries", name: "Spar", match: "Spar " },
  { category: "groceries", match: "ESTEC GASTRONOMY GROUP" },
  { category: "groceries", match: "Avondwinkel" },
  { category: "groceries", match: "Bakker Jongejans" },
  { category: "groceries", match: "Maas Versshop" },
  { category: "groceries", match: "Ekoplaza" },
  { category: "groceries", match: "BBROOD" },
  { category: "groceries", match: "Broodbakker" },
  { category: "groceries", match: "Kissbakery" },
  { category: "groceries", match: "Darya Market" },
  { category: "groceries", match: "DIRK" },
  { category: "groceries", match: "Paultjes Groenten" },
  { category: "groceries", match: "Fruittuin van West" },
  { category: "groceries", match: "foodello.nl" },
  { category: "groceries", match: "Gorillas" },
  { category: "groceries", match: "Groente & Fruit" },
  { category: "groceries", match: "LA FOURCHETTE" },
  { category: "groceries", match: "Jumbo" },
  { category: "groceries", match: "Lidl" },
  { category: "groceries", match: "Marqt" },
  { category: "groceries", match: "Olmenhorst" },
  { category: "groceries", match: "Spar City" },
  { category: "groceries", match: "Stach" },
  { category: "groceries", match: "Sterk Delicatessen" },
  { category: "groceries", match: "Twins Olive's" },
  { category: "groceries", match: "OLIVES" },
  { category: "groceries", match: "ALDI" },
  { category: "groceries", match: "Vishandel" },
  { category: "healthcare", match: "CZ Groep" },
  { category: "healthcare", match: "COVID" },
  {
    category: "healthcare",
    match: "L.M. Young-Afat",
    name: "Marriage counseling",
  },
  { category: "healthcare", match: "G.S.G.M. Puts - van Straeten" },
  {
    category: "healthcare",
    name: "Medical Science Purmerend",
    match: "Medical Science",
  },
  { category: "healthcare", match: "Kühler & Partners" },
  { category: "healthcare", match: "Inter-Being Psychologists" },
  { category: "healthcare", name: "Pharmacy", match: "apotheek" },
  { category: "healthcare", match: "VUmc" },
  { category: "healthcare", name: "Infomedics", match: "Infomedics B.V." },
  { category: "healthcare", match: "Infomedics" },
  { category: "healthcare", match: "FARMACIATEI" },
  { category: "healthcare", match: "FAMED" },
  { category: "healthcare", match: "Marlene Höning" },
  { category: "healthcare", match: "MEDLIFE" },
  { category: "healthcare", name: "Pharmacy", match: "Apotheke" },
  { category: "healthcare", name: "FAMED", match: "Fa-med" },
  { category: "relatives", match: "WWW.REGINAMARIA.RO" },
  { category: "home", match: "Blokker" },
  { category: "home", match: "etos" },
  { category: "home", match: "GREEN BUDGET BIKES" },
  { category: "home", match: "HEMA" },
  { category: "home", match: "Bouwmaat Amstel" },
  { category: "home", match: "IKEA" },
  { category: "home", match: "INTRATUIN" },
  { category: "home", match: "Kroes Advocaten Immigrat" },
  { category: "home", match: "Kruidvat" },
  { category: "home", match: "Plantenmarkt" },
  { category: "home", match: "Brandpreventiewinkel" },
  { category: "home", match: "Westwing" },
  { category: "home", match: "Reisbkh.Pied a Terre" },
  { category: "home", match: "De Tuinen" },
  { category: "icecream", match: "IJSCO" },
  { category: "icecream", match: "Sterk De Clerqstraat" },
  { category: "icecream", match: "IJsland Wereldijs" },
  { category: "icecream", match: "Dutch Food Concept" },
  { category: "icecream", match: "PISA IJS" },
  { category: "icecream", match: "G&M Gelato" },
  { category: "icecream", match: "Patagonias" },
  { category: "income", match: "BOOKING.COM B.V." },
  { category: "income", match: "EJR QUARTZ" },
  { category: "insurance", match: "ABN AMRO SCHADEV NV" },
  { category: "insurance", match: "Allianz Global" },
  { category: "insurance", match: "SCILDON" },
  { category: "insurance", match: "Zilveren Kruis" },
  { category: "insurance", match: "Maandpremie" },
  { category: "ignore", name: "Alocatie Alma", match: "AE ZINCULESCU" },
  { category: "ignore", name: "Alocatie Iris", match: "IM ZINCULESCU" },
  { category: "ignore", name: "Cont curent", match: "691394" },
  { category: "ignore", name: "Cont de economii", match: "992859" },
  { category: "ignore", name: "Cont de economii", match: "Economii" },
  { category: "ignore", name: "Facturi", match: "Cheltuieli fixe" },
  { category: "ignore", name: "Facturi", match: "Facturi" },
  { category: "ignore", match: "Naam: Vlad-Cristian Zinculescu" },
  { category: "ignore", match: "VC ZINCULESCU CJ" },
  { category: "ignore", name: "Degiro", match: "Flatex Bank" },
  {
    category: "ignore",
    name: "Notar Pamant",
    match: "Buma Algera Notariaat",
  },
  { category: "kids activities", match: "Muziekschool" },
  { category: "kids activities", match: "THE LITTLE GYM" },
  { category: "kids activities", match: "Amsterdamsche Football C" },
  {
    category: "kids activities",
    match: "De Basisclub & Dutch Club Omschrijving",
  },
  { category: "kids activities", match: "Dynamo" },
  { category: "kids activities", match: "R&A Sports" },
  { category: "kids activities", name: "Balet", match: "DMVS.Amsterdam B.V" },
  { category: "kids activities", match: "Judo Academie" },
  { category: "kids activities", match: "Teamshop.nl" },
  { category: "kids activities", match: "Snowworld" },
  { category: "kids activities", match: "iZ Micro Step" },
  {
    category: "kids activities",
    name: "Water Babies",
    match: "WB Amsterdam South",
  },
  { category: "childcare", match: "Sociale Verzekeringsbank" },
  { category: "kids activities", match: "SQULA" },
  { category: "learning", match: "Academie voor Coaching" },
  { category: "learning", match: "AJ&SMART" },
  { category: "learning", match: "ALLABOUTPARENTING.RO" },
  { category: "learning", match: "THE FUTUR" },
  { category: "learning", match: "EGGHEAD.IO" },
  {
    category: "learning",
    name: "Anne - Vlad's Interview Coach for Atlassian",
    match: "A.E. Galloway",
  },
  { category: "memories", match: "Dream Shots Boutique" },
  { category: "memories", match: "hetbordesfotografie" },
  { category: "mortgage", match: "Obvion N.V." },
  { category: "museum", match: "Rembr van gogh" },
  { category: "museum", match: "Stedelijk Museum" },
  { category: "museum", match: "Van Gogh Museum" },
  { category: "pets", match: "DK Buitenveldert" },
  { category: "pets", match: "Dierenshop" },
  { category: "pets", name: "Maatschap Dierenkliniek", match: "Dierenkl" },
  { category: "pets", match: "ZOOPLUS" },
  { category: "pets", match: "Dierenshop" },
  { category: "pets", name: "Asigurare Coco", match: "Petplan Polis" },
  { category: "pets", name: "Asigurare Coco", match: "Veterfina" },
  { category: "income", match: "Booking.com BV" },
  { category: "school", match: "Kindercampus Zuidas" },
  { category: "shit", match: "SPARKASSE ERDING-DORFE" },
  { category: "shopping", match: "Amazon" },
  { category: "diy", name: "AliExpress", match: "Alipay" },
  { category: "diy", match: "GAMMA" },
  { category: "diy", match: "Praxis" },
  { category: "shopping", match: "Marktplaats" },
  { category: "shopping", match: "Jacheta" },
  { category: "shopping", match: "G-LAB.COM" },
  { category: "shopping", match: "Wehkamp" },
  { category: "shopping", match: "DM-Drogerie" },
  { category: "shopping", match: "AMZN" },
  { category: "shopping", match: "Vinted" },
  { category: "shopping", match: "Bijenkorf" },
  { category: "shopping", match: "bol.com" },
  { category: "shopping", match: "BOLCOM" },
  { category: "shopping", match: "Imagine Wonderland" },
  { category: "shopping", match: "Action" },
  { category: "shopping", match: "Greenweez" },
  { category: "shopping", match: "V Karakas" },
  { category: "shopping", match: "Pomme Chatelaine" },
  { category: "shopping", match: "Sissy-Boy" },
  { category: "shopping", match: "Toppy B.V." },
  { category: "shopping", match: "Wijs West" },
  { category: "shopping", match: "Nooz Optics" },
  { category: "shopping", match: "Koninklijke PostNL" },
  { category: "shopping", name: "Coresi Brasov", match: "ZAHARIA STANCU NR 1" },
  { category: "shopping", name: "TkMaxx", match: "TJX NEDERLAND" },
  { category: "sport", match: "CHELIUS WORKOUTS" },
  { category: "sport", match: "ASANA REBEL BERLIN DEU" },
  { category: "sport", match: "HEARTCORE FOR LIFE" },
  { category: "sport", match: "HEARTCORE FOR LIFE" },
  { category: "sport", match: "PERRY SPORT" },
  { category: "sport", match: "Decathlon Arena" },
  { category: "sport", match: "DecathlonNetherlands" },
  { category: "sport", match: "Squash City" },
  { category: "sport", match: "ClassPass" },
  { category: "sport", match: "TOPROW ROEICENTRA" },
  { category: "sport", match: "Saints & Stars" },
  { category: "sport", match: "TOPROW ROEICENTRA" },
  { category: "sport", match: "ATHLETICGREENS" },
  { category: "sport", match: "Book Your Trainer" },
  { category: "sport", match: "Decathlon" },
  { category: "sport", match: "KINOSHITA" },
  { category: "taxes", match: "BELASTINGDIENST" },
  { category: "taxes", match: "D. Manova" },
  { category: "taxes", name: "Gemeente/Primarie", match: "Gemeente Amsterdam" },
  {
    category: "taxes",
    name: "Gemeente/Primarie",
    match: "Incasso Gemeente A msterdam Belastingen Termijn",
  },
  {
    category: "taxes",
    name: "Gemeente/Primarie",
    match: "Incasso Gemeente Amsterdam Belastingen Termijn",
  },
  { category: "taxes", name: "Rachid", match: "VOF Fidial" },
  { category: "taxes", match: "DGITL SECTOR 4" },
  { category: "tech", match: "NordVPN" },
  { category: "tech", match: "DIGITALOCEAN.COM" },
  { category: "tech", match: "GO DADDY" },
  { category: "tech", match: "EMAG.RO" },
  { category: "tech", match: "COOLBLUE" },
  { category: "tech", match: "Apple Store" },
  { category: "tech", match: "GRAMMARLY" },
  { category: "tech", match: "DROPBOX" },
  { category: "tech", name: "Apple Store", match: "APPLE.COM" },
  { category: "tickets", match: "EXPERCASH GmbH" },
  { category: "transport", match: "Fietsverhuur" },
  { category: "transport", match: "FREENOW" },
  { category: "transport", match: "NS Station Schiphol" },
  { category: "transport", match: "NS-" },
  { category: "transport", match: "OPLADENOV" },
  { category: "transport", match: "OV-CHIPKAART" },
  { category: "transport", match: "NS GROEP" },
  { category: "transport", match: "UBER   *TRIP" },
  { category: "transport", match: "UBER *TRIP" },
  { category: "transport", match: "BOLT.EU" },
  {
    category: "relatives",
    name: "Transport Aeroport Brasov",
    match: "M AND M EXPRESS MOBILP MUNICIPIUL",
  },
  { category: "transport", match: /^NS(-|\s)/ },
  { category: "transport", match: /GVB/ },
  { category: "utilities", match: "Vandebron Energie" },
  { category: "utilities", match: "ZIGGO SERVICES" },
  { category: "utilities", match: "Waterschap" },
  { category: "utilities", match: "T-Mobile" },
  { category: "utilities", match: "Waternet" },
  { category: "VvE", name: "VvE Weerdestein", match: "VVE WONING WEERDESTEIN" },
  {
    category: "VvE",
    name: "VvE Weerdestein",
    match: "VvE Woningen in Gebouw Weerdestein",
  },
  { category: "realestate", name: "ABN Amro", match: "NL33ABNA0432408118" },
  {
    category: "realestate",
    name: "VvE van Nijenrodeweg",
    match: "VVE BACKERSHAGEN",
  },
  { category: "realestate", name: "Jawad", match: "J SHAFKAT CJ" },
  { category: "realestate", match: "Vastgoed Unie Beheer" },
  { category: "miscelaneous", match: "Tikkie" },
];
