export default [
  { category: "bank fees", match: "Your monthly statement is" },
  { category: "beauty", match: "PPopNL" },
  { category: "beauty", match: "CLINIC PURE" },
  { category: "beauty", match: "The Wax Bar" },
  { category: "beauty", match: "LAKWERK" },
  { category: "beauty", match: "GLOW2GO" },
  { category: "bike", match: "Dolly" },
  { category: "books", match: "AMERICAN BOOK CENTER" },
  { category: "car", match: "ANWB" },
  { category: "car", match: "Centraal Beheer" },
  { category: "car", match: "FRANK VANEMAN AUTO" },
  { category: "car", match: "SHELL" },
  { category: "car", match: "Veilig B.V." },
  { category: "car", match: "Abswoude" },
  { category: "car", match: "Wisselautomaten.nl" },
  { category: "car", match: "LoogmanTanken&Wassen" },
  { category: "car", match: "PI ZD Zentrale Bußgeldstelle" },
  { category: "car", match: "Loogman Tanken" },
  { category: "car", match: "Parkeren" },
  { category: "car", match: "Parkeergarage" },
  { category: "car", match: "Parking" },
  { category: "car", name: "Parking", match: "MOBILITEITSGELDEN" },
  { category: "cash", match: "AANKOMST SCHIPHOL PLAZA" },
  { category: "cash", match: "Geldmaat" },
  { category: "cash", match: "ING AMSTERDAM" },
  { category: "cash", match: "ING SCHIPHOL PLAZ" },
  { category: "cash", match: "JAN VAN GALENSTR 86" },
  { category: "cash", match: "JODENBREESTRAAT 96" },
  { category: "cash", match: "UTRECHTSESTRAAT 13" },
  { category: "charity", match: "Stichting Save the Children" },
  { category: "childcare", match: "CompaNanny" },
  { category: "childcare", match: "KinderRijk" },
  { category: "cleaning", match: "Carolina Robayo Correa" },
  { category: "clothes", match: "Bever" },
  { category: "clothes", match: "OYSHO.COM" },
  { category: "clothes", match: "WOMENSECRET" },
  { category: "clothes", match: "IELM.RO" },
  { category: "clothes", match: "DIESEL STORE" },
  { category: "clothes", match: "ESPRIT" },
  { category: "clothes", match: "Limango" },
  { category: "clothes", match: "Onitjuka Tiger" },
  { category: "clothes", match: "UNIQLO" },
  { category: "clothes", match: "Nike" },
  { category: "clothes", match: "Adidas" },
  { category: "clothes", match: "C&A" },
  { category: "clothes", match: "ARKET" },
  { category: "clothes", match: "ZARA" },
  { category: "clothes", match: "URBAN OUTFITTERS" },
  {
    category: "clothes",
    name: "Limango",
    match: "STICHTING DERDENGELDEN BUCKAROO",
  },
  { category: "coffee", match: "BOABE SI STRUGURI" },
  { category: "coffee", match: "BREAD & SPICES" },
  { category: "coffee", match: "Cafe Nord" },
  { category: "coffee", match: "Caffenation" },
  { category: "coffee", name: "Coffee District", match: "Coffee Distri" },
  { category: "coffee", match: "Coffee District" },
  { category: "coffee", match: "Coffee Comp" },
  { category: "coffee", match: "Badeta Coffee" },
  { category: "coffee", match: "Gogol BV" },
  { category: "coffee", match: "Guji B.V." },
  { category: "coffee", match: "Coffee Bru" },
  { category: "coffee", match: "De Uitsmijter" },
  { category: "coffee", match: "YUSU" },
  { category: "coffee", match: "VASCOBELO" },
  { category: "coffee", match: "Caffe Minerva" },
  { category: "coffee", match: "BRANDMEESTER" },
  { category: "coffee", match: "CoffeeCompany" },
  { category: "coffee", match: "Back To Black" },
  { category: "coffee", name: "Lebkov&Sons", match: "Lebkov@Sons" },
  {
    category: "coffee",
    name: "Scandinavian Embassy",
    match: "Scandinavian Embassy",
  },
  {
    category: "coffee",
    name: "Scandinavian Embassy",
    match: "SumUp Scandinavian",
  },
  {
    category: "coffee",
    name: "Scandinavian Embassy",
    match: "ScandinavianEmbassy",
  },
  { category: "concerts", match: "Paradiso" },
  { category: "creditcard", match: "INT CARD SERVICES" },
  { category: "creditcard", match: "International Card Services B.V." },
  { category: "crypto", match: "transak.com" },
  { category: "drugs", match: "DAM APOTHEEK" },
  { category: "entertainment", match: "A Space Oddity" },
  { category: "entertainment", match: "Boekhandel" },
  { category: "entertainment", match: "EDENLAND" },
  { category: "entertainment", match: "CINEMACITY" },
  { category: "entertainment", match: "Artis" },
  { category: "entertainment", match: "ATHENAEUM SPUI" },
  { category: "entertainment", match: "Kiddieland" },
  { category: "entertainment", match: "Amstelpark" },
  { category: "entertainment", match: "Speeltuin Amstelpark" },
  { category: "entertainment", match: "ATHENAEUM SPUI" },
  { category: "entertainment", match: "Amsterdam Spanish Film Festival" },
  { category: "entertainment", match: "Bouldergym en Restaura" },
  { category: "entertainment", match: "EYE FILMINSTITUUT" },
  { category: "entertainment", match: "KNIJN BOWLING" },
  { category: "entertainment", match: "Knijn Bowling BV" },
  { category: "entertainment", match: "Kriterion" },
  { category: "entertainment", match: "PAYPAL *NOLIMITES" },
  { category: "entertainment", match: "CINEPLEXX" },
  { category: "entertainment", match: "LANDAL GREENPARKS" },
  { category: "entertainment", match: "MM Amsterdam Centrum" },
  { category: "entertainment", match: "NSC AMS" },
  { category: "entertainment", match: "Space Expo" },
  { category: "entertainment", match: "OFFICIALMERCHANDISE" },
  { category: "entertainment", match: "OPENBARE BIBLIOT" },
  { category: "entertainment", match: "Bibliotheek" },
  { category: "entertainment", match: "Concertgebouw" },
  { category: "entertainment", match: "P Pop" },
  { category: "entertainment", match: "Pathe" },
  { category: "entertainment", match: "The New English Bookst" },
  { category: "entertainment", match: "Ticketmaster" },
  { category: "entertainment", match: "Floriade" },
  { category: "entertainment", match: "MIDGETGOLF" },
  { category: "entertainment", match: "De Nationale Theaterkassa" },
  { category: "entertainment", match: "Het Nationale Park" },
  { category: "entertainment", match: "AUDIBLE" },
  { category: "entertainment", match: "NETFLIX" },
  { category: "entertainment", match: "DISNEY" },
  { category: "entertainment", match: "APPLE.COM" },
  {
    category: "entertainment",
    name: "Kiddieland",
    match: "Ypex-Gelderlandpln",
  },
  { category: "entertainment", match: "Ziggo Dome" },
  { category: "entertainment", match: "VOXA.RO" },

  { category: "food", match: "Asian Kitchen" },
  { category: "food", match: "Bagels & Beans" },
  { category: "food", match: "BAGELS AND BEANS" },
  { category: "food", match: "Club Botanica" },
  { category: "food", match: "BAGELS EN BEANS" },
  { category: "food", match: "Vlaamsch Broodhuys" },
  { category: "food", match: "Bakkerswinkel" },
  { category: "food", match: "Bakkerskar" },
  { category: "food", match: "BAR BROUW" },
  { category: "food", match: "Bar Moustache" },
  { category: "food", match: "Chun Amsterdam" },
  { category: "food", match: "BAR PITA AMSTERDAM" },
  { category: "food", match: "BeerTemple" },
  { category: "food", match: "Bakkerij Lunchroom" },
  { category: "food", match: "BIRD THAIS REST" },
  { category: "food", match: "Indian Quality" },
  { category: "food", match: "Blos Horeca" },
  { category: "food", match: "BRUG 34" },
  { category: "food", match: "BURGER BAR" },
  { category: "food", match: "BURGERIJ" },
  { category: "food", match: "Pedevilla" },
  { category: "food", match: "BURGERMEESTER" },
  { category: "food", match: "BURGERZAKEN" },
  { category: "food", match: "Fort Negen" },
  { category: "food", match: "Joe And The Juice" },
  { category: "food", match: "Cafe de Jaren" },
  { category: "food", match: "Cafe De Raedt" },
  { category: "food", match: "cafe Katoen" },
  { category: "food", match: "CALIFORNIA BURRITO" },
  { category: "food", match: "CANNIBALE" },
  { category: "food", match: "CCV CAMEEL BV" },
  { category: "food", match: "de Doelen" },
  { category: "food", match: "De Haven" },
  { category: "food", match: "Delicatesse Shilla" },
  { category: "food", match: "Smulday Turkse" },
  { category: "food", match: "Deliveroo" },
  { category: "food", match: "DeOudeDoelen" },
  { category: "food", match: "Dim Sum Court" },
  { category: "food", match: "DOMINOS" },
  { category: "food", match: "DONER COMPANY" },
  { category: "food", match: "Doner Plaza" },
  { category: "food", match: "Eat Mode" },
  { category: "food", match: "EAZIE" },
  { category: "food", match: "FIER" },
  { category: "food", match: "FOODHALLEN" },
  { category: "food", match: "MarleenKookt BV" },
  { category: "food", match: "Fou Fow ramen" },
  { category: "food", match: "Frozz B.V" },
  { category: "food", match: "Gasthuijs" },
  { category: "food", match: "Gollem" },
  { category: "food", match: "Good Fortune" },
  { category: "food", match: "Grand Cafe de Balie" },
  { category: "food", match: "Greenbrothers" },
  { category: "food", match: "Greenwoods" },
  { category: "food", match: "Happy italy" },
  { category: "food", match: "HavenrestaurantTexel" },
  { category: "food", match: "HEEREN" },
  { category: "food", match: "HMSHOST AMSTERDAM SCHI" },
  { category: "food", match: "Hong Kong Superstore" },
  { category: "food", match: "Hoppy Days" },
  { category: "food", match: "House of Bird" },
  { category: "food", match: "Hummbar" },
  { category: "food", match: "Jabugo bar Iberico" },
  { category: "food", match: "PELANGI GRILL" },
  { category: "food", match: "Jamin Amsterdam" },
  { category: "food", match: "Julias" },
  { category: "food", match: "Kam Yin" },
  { category: "food", match: "Kohinoor" },
  { category: "food", match: "La Place" },
  { category: "food", match: "Latei" },
  { category: "food", match: "Le Big Fish" },
  { category: "food", match: "MAOZ FALAFAL" },
  { category: "food", match: "MAOZ FALAFEL" },
  { category: "food", match: "Mata Hari" },
  { category: "food", match: "MC DONALDS" },
  { category: "food", match: "McDonald" },
  { category: "food", match: "MENEER TEMAKI" },
  { category: "food", match: "Mezzave" },
  { category: "food", match: "Monkey Chief Tea" },
  { category: "food", match: "Martinot" },
  { category: "food", match: "Moeders" },
  { category: "food", match: "Moeke's Maaltijd" },
  { category: "food", match: "BruiZZ" },
  { category: "food", match: "MOOK PANCAKES" },
  { category: "food", match: "MULTIFOODEXPRESS" },
  { category: "food", match: "Park Kiosk" },
  { category: "food", match: "Nassau" },
  { category: "food", match: "NES CAFE" },
  { category: "food", match: "NEW YORK PIZZA" },
  { category: "food", match: "Noodlebar" },
  { category: "food", match: "O mai Amsterdam" },
  { category: "food", match: "OMELEGG" },
  { category: "food", match: "OUDE ZIJDS HORECA" },
  { category: "food", match: "PHO VIET" },
  { category: "food", match: "Pizzabakkers" },
  { category: "food", match: "pizzeria" },
  { category: "food", match: "Portare Via" },
  { category: "food", match: "Praellokaal" },
  { category: "food", match: "QUICK 747" },
  { category: "food", match: "Radijs" },
  { category: "food", match: "RAMEN YA" },
  { category: "food", match: "ROEST" },
  { category: "food", match: "SALSA SHOP" },
  { category: "food", match: "Soup en Zo" },
  { category: "food", match: "Starbuc" },
  { category: "food", match: "STARBUCKS" },
  { category: "food", match: "Storm B.V. ZANDVOORT" },
  { category: "food", match: "TAVERNA BARCELONA" },
  { category: "food", match: "Teddy`s Grill" },
  { category: "food", match: "Terrasmus" },
  { category: "food", match: "THE BREAKFAST CLUB" },
  { category: "food", match: "THE BUTCHER" },
  { category: "food", match: "THE DUTCH CO" },
  { category: "food", match: "The Rough Kitchen" },
  { category: "food", match: "VAN DE BUURT" },
  { category: "food", match: "Van Meggelen" },
  { category: "food", match: "VAN T SPIT" },
  { category: "food", match: "Poke Perfect" },
  { category: "food", match: "Urban Salad" },
  { category: "food", match: "Venkel" },
  { category: "food", match: "UBER *EATS" },
  { category: "food", match: "VERTREK 2/LOUNGE 2 2ET" },
  { category: "food", match: "VIJZELSTRAAT BY TE A" },
  { category: "food", match: "VITAMINSTORE" },
  { category: "food", match: "Vof Blaauwhooft" },
  { category: "food", match: "Volendammer Vishande" },
  { category: "food", match: "De Waldhoorn" },
  { category: "food", match: "Wagamama" },
  { category: "food", match: "Winkel 43" },
  { category: "food", match: "Wok To Go" },
  { category: "food", match: "YOGEN FRUZ" },
  { category: "food", match: "Mana Mana" },
  { category: "food", match: "Ysbreker" },
  { category: "food", match: "SLA ASW" },
  { category: "food", match: "pizza" },
  { category: "food", match: "Pizza Boys" },
  { category: "food", match: "The Food Loving" },
  { category: "food", match: "tHuis aan de Amstel" },
  { category: "food", match: "Loetje" },
  { category: "food", match: "Bakhuys" },
  { category: "food", match: "Puccini" },
  { category: "food", match: "ZUCCA LEIDEN" },
  { category: "food", match: "GRACECC.RO" },
  { category: "food", match: /^Febo/ },
  { category: "food", match: /BRASSERIE/i },
  { category: "food", match: /cafe/i },
  { category: "food", match: /horeca/i }, // https://en.wikipedia.org/wiki/Hor
  { category: "food", name: "Restaurant", match: /RESTAURANT/i },
  { category: "food", name: "Bagels and Beans", match: "SALOMON LUNCH" },
  { category: "food", name: "Bar Jones", match: "DE BRAKKE GROND" },
  { category: "food", name: "Burger King", match: "BK 13462" },
  { category: "food", name: "Cafe De Klos", match: "BGN WEST BV" },
  { category: "food", name: "Elsevier Cafe", match: "Reed Elsevier A'dam" },
  { category: "food", name: "Hutten Business", match: "Hutten Business" },
  { category: "food", name: "Lucky House", match: "Lucky House" },
  { category: "food", name: "Wannemakers!", match: "Zhu Lin VOF" },
  { category: "food", name: "Wok To Walk Dam", match: "CCV WOK DAMSTRAAT" },
  { category: "food", name: "Vlad's friends", match: "IC Polli" },
  { category: "food", name: "Vlad's friends", match: "Rovira i Bonet" },
  { category: "food", name: "Wok To Walk", match: "DOV MELO" },
  { category: "food", note: "burgers", match: "Prime Cuts BV" },
  { category: "food", note: "near", match: "Corner Admiraal" },
  { category: "food", match: "Takumi Ramen Kitchen" },
  { category: "gifts", match: "Babypark Kesteren BV" },
  { category: "gifts", match: "Bloemen" },
  { category: "gifts", match: "Koffiejongens" },
  { category: "gifts", match: "LOCO FABRIEK" },
  { category: "gifts", match: "YourSurprise.com" },
  { category: "gifts", match: "Zwaan en van Slooten" },
  { category: "gifts", match: "Rituals" },
  { category: "gifts", match: "INTERTOYS" },
  { category: "gifts", match: "Cedille" },
  { category: "gifts", match: "Kids Toys World" },
  { category: "gifts", match: "Greetz.nl" },
  { category: "groceries", match: "AH to go" },
  { category: "groceries", match: "BEBETEI" },
  { category: "groceries", match: "FRESHFUL.RO" },
  { category: "groceries", match: "Albert Heijn" },
  { category: "groceries", match: "Ankara Market" },
  { category: "groceries", match: "Crowdbutching.com" },
  { category: "groceries", match: "Gall & Gall" },
  { category: "groceries", name: "Spar", match: "Spar " },
  { category: "groceries", match: "ESTEC GASTRONOMY GROUP" },
  { category: "groceries", match: "Avondwinkel" },
  { category: "groceries", match: "Bakker Jongejans" },
  { category: "groceries", match: "Maas Versshop" },
  { category: "groceries", match: "Ekoplaza" },
  { category: "groceries", match: "BBROOD" },
  { category: "groceries", match: "Broodbakker" },
  { category: "groceries", match: "Kissbakery" },
  { category: "groceries", match: "Darya Market" },
  { category: "groceries", match: "DIRK" },
  { category: "groceries", match: "Paultjes Groenten" },
  { category: "groceries", match: "Fruittuin van West" },
  { category: "groceries", match: "foodello.nl" },
  { category: "groceries", match: "Gorillas" },
  { category: "groceries", match: "Groente & Fruit" },
  { category: "groceries", match: "LA FOURCHETTE" },
  { category: "groceries", match: "Jumbo" },
  { category: "groceries", match: "Lidl" },
  { category: "groceries", match: "Marqt" },
  { category: "groceries", match: "Olmenhorst" },
  { category: "groceries", match: "Spar City" },
  { category: "groceries", match: "Stach" },
  { category: "groceries", match: "Sterk Delicatessen" },
  { category: "groceries", match: "Twins Olive's" },
  { category: "groceries", match: "OLIVES" },
  { category: "groceries", match: "ALDI" },
  { category: "groceries", match: "Vishandel" },
  { category: "haircut", match: "Cut by Mario" },
  { category: "healthcare", match: "CZ Groep" },
  { category: "healthcare", match: "Kühler & Partners" },
  { category: "healthcare", match: "apotheek" },
  { category: "healthcare", match: "VUmc" },
  { category: "healthcare", match: "Infomedics B.V." },
  { category: "healthcare", match: "Holland & Barrett" },
  { category: "healthcare", match: "FARMACIATEI" },
  { category: "relatives", match: "WWW.REGINAMARIA.RO" },
  { category: "home", match: "Blokker" },
  { category: "home", match: "etos" },
  { category: "home", match: "GREEN BUDGET BIKES" },
  { category: "home", match: "HEMA" },
  { category: "home", match: "HORNBACH" },
  { category: "home", match: "Bouwmaat Amstel" },
  { category: "home", match: "IKEA" },
  { category: "home", match: "INTRATUIN" },
  { category: "home", match: "Kroes Advocaten Immigrat" },
  { category: "home", match: "Kruidvat" },
  { category: "home", match: "GAMMA" },
  { category: "home", match: "Plantenmarkt" },
  { category: "home", match: "PostNL AMSTERDAM" },
  { category: "home", match: "Praxis" },
  { category: "home", match: "Brandpreventiewinkel" },
  { category: "home", match: "Reisbkh.Pied a Terre" },
  { category: "icecream", match: "IJSCO" },
  { category: "icecream", match: "IJsland Wereldijs" },
  { category: "icecream", match: "Dutch Food Concept" },
  { category: "icecream", match: "PISA IJS" },
  { category: "icecream", match: "G&M Gelato" },
  { category: "icecream", match: "Patagonias" },
  { category: "income", match: "BOOKING.COM B.V." },
  { category: "income", match: "EJR QUARTZ" },
  { category: "insurance", match: "ABN AMRO SCHADEV NV" },
  { category: "insurance", match: "Allianz Global" },
  { category: "insurance", match: "SCILDON" },
  { category: "insurance", match: "Zilveren Kruis" },
  { category: "internal", name: "Alocatie Alma", match: "AE ZINCULESCU" },
  { category: "internal", name: "Alocatie Iris", match: "IM ZINCULESCU" },
  { category: "internal", name: "Cont curent", match: "691394" },
  { category: "internal", name: "Cont de economii", match: "992859" },
  { category: "internal", name: "Facturi", match: "Cheltuieli fixe" },
  { category: "internal", name: "Facturi", match: "Facturi" },
  { category: "kids activities", match: "Muziekschool" },
  { category: "kids activities", match: "Amsterdamsche Football C" },
  {
    category: "kids activities",
    match: "De Basisclub & Dutch Club Omschrijving",
  },
  { category: "kids activities", match: "Dynamo" },
  { category: "kids activities", match: "R&A Sports" },
  { category: "kids activities", match: "Judo Academie" },
  { category: "kids activities", match: "Teamshop.nl" },
  {
    category: "kids activities",
    name: "Water Babies",
    match: "WB Amsterdam South",
  },
  { category: "kids allowance", match: "Sociale Verzekeringsbank" },
  { category: "kids allowance", match: "SQULA" },
  { category: "memories", match: "Dream Shots Boutique" },
  { category: "memories", match: "hetbordesfotografie" },
  { category: "mortgage", name: "ABN Amro", match: "NL33ABNA0432408118" },
  { category: "mortgage", match: "Obvion N.V." },
  { category: "museum", match: "Rembr van gogh" },
  { category: "museum", match: "Stedelijk Museum" },
  { category: "museum", match: "Van Gogh Museum" },
  { category: "pets", match: "DK Buitenveldert" },
  { category: "pets", match: "Dierenshop" },
  { category: "pets", match: "ZOOPLUS" },
  { category: "pets", match: "Dierenshop" },
  { category: "rent", match: "Vastgoed Unie Beheer" },
  { category: "income", match: "Booking.com BV" },
  { category: "school", match: "Kindercampus Zuidas" },
  { category: "shit", match: "SPARKASSE ERDING-DORFE" },
  { category: "shopping", match: "Amazon" },
  { category: "shopping", match: "DM-Drogerie" },
  { category: "shopping", match: "AMZN" },
  { category: "shopping", match: "Vinted" },
  { category: "shopping", match: "Bijenkorf" },
  { category: "shopping", match: "bol.com" },
  { category: "shopping", match: "Imagine Wonderland" },
  { category: "shopping", match: "Zalando" },
  { category: "shopping", match: "Action" },
  { category: "shopping", match: "Greenweez" },
  { category: "shopping", match: "V Karakas" },
  { category: "shopping", match: "Pomme Chatelaine" },
  { category: "shopping", match: "Sissy-Boy" },
  { category: "shopping", name: "Coresi Brasov", match: "ZAHARIA STANCU NR 1" },
  { category: "shopping", name: "TkMaxx", match: "TJX NEDERLAND" },
  { category: "sport", match: "CHELIUS WORKOUTS" },
  { category: "sport", match: "HEARTCORE FOR LIFE" },
  { category: "sport", match: "PERRY SPORT" },
  { category: "sport", match: "Decathlon Arena" },
  { category: "sport", match: "DecathlonNetherlands" },
  { category: "sport", match: "Squash City" },
  { category: "sport", match: "ClassPass" },
  { category: "sport", match: "TOPROW ROEICENTRA" },
  { category: "sport", match: "Saints & Stars" },
  { category: "sport", match: "TOPROW ROEICENTRA" },
  { category: "sport", match: "ATHLETICGREENS" },
  { category: "sport", match: "Book Your Trainer" },
  { category: "stocks", match: "Flatex Bank" },
  { category: "taxes", match: "BELASTINGDIENST" },
  { category: "taxes", name: "Gemeente/Primarie", match: "Gemeente Amsterdam" },
  {
    category: "taxes",
    name: "Gemeente/Primarie",
    match: "Incasso Gemeente A msterdam Belastingen Termijn",
  },
  {
    category: "taxes",
    name: "Gemeente/Primarie",
    match: "Incasso Gemeente Amsterdam Belastingen Termijn",
  },
  { category: "taxes", name: "Rachid", match: "VOF Fidial" },
  { category: "taxes", match: "DGITL SECTOR 4" },
  { category: "tech", match: "NordVPN" },
  { category: "tech", match: "DIGITALOCEAN.COM" },
  { category: "tech", match: "GO DADDY" },
  { category: "tech", match: "EMAG.RO" },
  { category: "tech", match: "COOLBLUE" },
  { category: "tickets", match: "EXPERCASH GmbH" },
  { category: "transport", match: "Fietsverhuur" },
  { category: "transport", match: "FREENOW" },
  { category: "transport", match: "RATBV" },
  { category: "transport", match: "STB SA BUCURESTI" },
  { category: "transport", match: "NS Station Schiphol" },
  { category: "transport", match: "NS-" },
  { category: "transport", match: "OPLADENOV" },
  { category: "transport", match: "OV-CHIPKAART" },
  { category: "transport", match: "NS GROEP" },
  { category: "transport", match: "UBER   *TRIP" },
  { category: "transport", match: "UBER *TRIP" },
  { category: "transport", match: "BOLT.EU" },
  {
    category: "transport",
    name: "Transport Aeroport Brasov",
    match: "M AND M EXPRESS MOBILP MUNICIPIUL",
  },
  { category: "transport", match: /^NS(-|\s)/ },
  { category: "transport", match: /GVB/ },
  { category: "travel", match: "Global Collect BV" },
  { category: "travel", match: "GlobalCollect" },
  { category: "travel", match: "HMS Host International" },
  { category: "travel", match: "HOTEL BERGHOF" },
  { category: "travel", match: "KLM" },
  { category: "travel", match: "Kroonenberg Groep" },
  { category: "travel", match: "Landal Miggelenberg" },
  { category: "travel", match: "LANDAL.NL" },
  { category: "travel", match: "LUCHTHAVEN Schip" },
  { category: "travel", match: "REWE" },
  { category: "travel", name: "Restaurant LEMONOKIPOS", match: "LEMONOKIPOS" },
  { category: "travel", match: "motel" },
  {
    category: "travel",
    name: "Echipamente Ski Austria",
    match: "Sport Wegscheider",
  },
  {
    category: "travel",
    name: "Telecabina Austria",
    match: "Penkenbahn",
  },
  {
    category: "travel",
    name: "Scoala Ski Austria",
    match: "SMT Mayrhofen",
  },
  { category: "travel", match: "MYTRIP" },
  { category: "travel", match: "RENTALCARS.COM" },
  { category: "travel", match: "RENT-A-CAR" },
  { category: "travel", match: "Schiphol" },
  { category: "travel", match: "STG ADYEN" },
  { category: "travel", match: "TAROM" },
  { category: "travel", match: "Wilde  Moeflon" },
  { category: "travel", match: "ZAGAZAGA" },
  { category: "travel", match: "FERMA PENTELEU" },
  { category: "travel", name: "Madrid", match: "IBEXPRESS060230491260" },
  { category: "travel", name: "Booking.com", match: "Hotel at Booking.com" },
  { category: "travel", match: "hotel" },
  { category: "travel", name: "Payment in Romania", match: "Land: RO" },
  { category: "travel", name: "Payment in Greece", match: "Land: GR" },
  { category: "travel", name: "Payment in Germany", match: "Land: DE" },
  { category: "travel", name: "Payment in Italy", match: "Land: IT" },
  { category: "travel", name: "Payment in France", match: "Land: FR" },
  { category: "travel", name: "Payment in Portugal", match: "Land: PT" },
  { category: "travel", name: "Payment in Belgium", match: "Land: BE" },
  { category: "travel", name: "Payment in Poland", match: "Land: PL" },
  { category: "travel", name: "Payment in Austria", match: "Land: AT" },
  { category: "travel", name: "Payment in Spain", match: "Land: ES" },
  { category: "travel", name: "Payment abroad", match: "Land: " },
  { category: "utilities", match: "Vandebron Energie" },
  { category: "utilities", match: "ZIGGO SERVICES" },
  { category: "utilities", match: "Waterschap" },
  { category: "utilities", match: "T-Mobile" },
  { category: "VvE", name: "VvE van Nijenrodeweg", match: "VVE BACKERSHAGEN" },
  { category: "VvE", name: "VvE Weerdestein", match: "VVE WONING WEERDESTEIN" },
  { category: "VvE", name: "Jawad", match: "J SHAFKAT CJ" },
  {
    category: "VvE",
    name: "VvE Weerdestein",
    match: "VvE Woningen in Gebouw Weerdestein",
  },
];
